[tool.ruff]
extend-exclude = ["database/models.py", "**/__init__.py"]
fix = true
indent-width = 4
line-length = 90
show-fixes = true
target-version="py312"


[tool.pytest.ini_options]
pythonpath = [
  ".",
]
asyncio_mode="auto"